annotations:
  category: Infrastructure
  licenses: Apache-2.0
apiVersion: v2
appVersion: 2.2.0
dependencies:
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - bitnami-common
    version: 2.x.x
description: The RabbitMQ Cluster Kubernetes Operator automates provisioning, management, and operations of RabbitMQ clusters running on Kubernetes.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/rabbitmq-cluster-operator/img/rabbitmq-cluster-operator-stack-220x234.png
keywords:
  - rabbitmq
  - operator
  - infrastructure
  - message queue
  - AMQP
kubeVersion: '>= 1.19.0-0'
maintainers:
  - name: VMware, Inc.
    url: https://github.com/bitnami/charts
name: rabbitmq-cluster-operator
sources:
  - https://github.com/bitnami/charts/tree/main/bitnami/rabbitmq-cluster-operator
version: 3.4.0
