annotations:
  category: DeveloperTools
  licenses: Apache-2.0
apiVersion: v2
appVersion: 7.0.5
dependencies:
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - bitnami-common
    version: 2.x.x
description: ASP.NET Core is an open-source framework for web application development created by Microsoft. It runs on both the full .NET Framework, on Windows, and the cross-platform .NET Core.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/aspnet-core/img/aspnet-core-stack-220x234.png
keywords:
  - asp.net
  - dotnet
maintainers:
  - name: VMware, Inc.
    url: https://github.com/bitnami/charts
name: aspnet-core
sources:
  - https://github.com/bitnami/charts/tree/main/bitnami/aspnet-core
version: 4.2.0
