annotations:
  category: Infrastructure
  licenses: Apache-2.0
apiVersion: v2
appVersion: 1.0.7
dependencies:
  - condition: wavefront.enabled
    name: wavefront
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 4.x.x
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - bitnami-common
    version: 2.x.x
description: Wavefront Storage Adapter is a Prometheus integration to transfer metrics from Prometheus to Wavefront. It lets you save Prometheus data in Wavefront without changing your existing Prometheus setup.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/wavefront-prometheus-storage-adapter/img/wavefront-prometheus-storage-adapter-stack-220x234.png
keywords:
  - alerting
  - adapter
  - metrics
  - monitoring
  - observability
  - wavefront
maintainers:
  - name: VMware, Inc.
    url: https://github.com/bitnami/charts
name: wavefront-prometheus-storage-adapter
sources:
  - https://github.com/bitnami/charts/tree/main/bitnami/wavefront-prometheus-storage-adapter
version: 2.3.0
