apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: influxdb
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.influxdb.service.annotations .Values.commonAnnotations }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
    {{- end }}
    {{- if .Values.influxdb.service.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.influxdb.service.annotations "context" $) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.influxdb.service.type }}
  {{- if and .Values.influxdb.service.clusterIP (eq .Values.influxdb.service.type "ClusterIP") }}
  clusterIP: {{ .Values.influxdb.service.clusterIP }}
  {{- end }}
  {{- if (or (eq .Values.influxdb.service.type "LoadBalancer") (eq .Values.influxdb.service.type "NodePort")) }}
  externalTrafficPolicy: {{ .Values.influxdb.service.externalTrafficPolicy | quote }}
  {{- end }}
  {{- if eq .Values.influxdb.service.type "LoadBalancer" }}
  loadBalancerSourceRanges: {{ .Values.influxdb.service.loadBalancerSourceRanges }}
  {{- end }}
  {{- if (and (eq .Values.influxdb.service.type "LoadBalancer") (not (empty .Values.influxdb.service.loadBalancerIP))) }}
  loadBalancerIP: {{ .Values.influxdb.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.influxdb.service.sessionAffinity }}
  sessionAffinity: {{ .Values.influxdb.service.sessionAffinity }}
  {{- end }}
  {{- if .Values.influxdb.service.sessionAffinityConfig }}
  sessionAffinityConfig: {{- include "common.tplvalues.render" (dict "value" .Values.influxdb.service.sessionAffinityConfig "context" $) | nindent 4 }}
  {{- end }}
  ports:
    - port: {{ coalesce .Values.influxdb.service.ports.http .Values.influxdb.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if (and (or (eq .Values.influxdb.service.type "NodePort") (eq .Values.influxdb.service.type "LoadBalancer")) (not (empty .Values.influxdb.service.nodePorts.http))) }}
      nodePort: {{ .Values.influxdb.service.nodePorts.http }}
      {{- else if eq .Values.influxdb.service.type "ClusterIP" }}
      nodePort: null
      {{- end }}
    - port: {{ coalesce .Values.influxdb.service.ports.rpc .Values.influxdb.service.rpcPort }}
      targetPort: rpc
      protocol: TCP
      name: rpc
      {{- if (and (or (eq .Values.influxdb.service.type "NodePort") (eq .Values.influxdb.service.type "LoadBalancer")) (not (empty .Values.influxdb.service.nodePorts.rpc))) }}
      nodePort: {{ .Values.influxdb.service.nodePorts.rpc }}
      {{- else if eq .Values.influxdb.service.type "ClusterIP" }}
      nodePort: null
      {{- end }}
    {{- if .Values.influxdb.service.extraPorts }}
    {{- include "common.tplvalues.render" (dict "value" .Values.influxdb.service.extraPorts "context" $) | nindent 4 }}
    {{- end }}
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: influxdb
