annotations:
  category: Infrastructure
  licenses: Apache-2.0
apiVersion: v2
appVersion: 0.9.10
dependencies:
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - bitnami-common
    version: 2.x.x
description: Wavefront HPA Adapter for Kubernetes is a Kubernetes Horizontal Pod Autoscaler adapter. It allows to scale your Kubernetes workloads based on Wavefront metrics.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/wavefront-hpa-adapter/img/wavefront-hpa-adapter-stack-220x234.png
keywords:
  - alerting
  - adapter
  - metrics
  - monitoring
  - observability
  - wavefront
maintainers:
  - name: VMware, Inc.
    url: https://github.com/bitnami/charts
name: wavefront-hpa-adapter
sources:
  - https://github.com/bitnami/charts/tree/main/bitnami/wavefront-hpa-adapter
version: 1.5.0
