annotations:
  category: E-Commerce
  licenses: Apache-2.0
apiVersion: v2
appVersion: 8.0.4
dependencies:
  - condition: mariadb.enabled
    name: mariadb
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 12.x.x
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - bitnami-common
    version: 2.x.x
description: PrestaShop is a powerful open source eCommerce platform used by over 250,000 online storefronts worldwide. It is easily customizable, responsive, and includes powerful tools to drive online sales.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/prestashop/img/prestashop-stack-220x234.png
keywords:
  - prestashop
  - e-commerce
  - http
  - web
  - php
maintainers:
  - name: VMware, Inc.
    url: https://github.com/bitnami/charts
name: prestashop
sources:
  - https://github.com/bitnami/charts/tree/main/bitnami/prestashop
version: 17.1.1
