{{- if .Values.realtime.enabled }}
apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ template "supabase.realtime.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/part-of: supabase
    app.kubernetes.io/component: realtime
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.realtime.replicaCount }}
  {{- if .Values.realtime.updateStrategy }}
  strategy: {{- toYaml .Values.realtime.updateStrategy | nindent 4 }}
  {{- end }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: realtime
  template:
    metadata:
      annotations:
        {{- if .Values.realtime.podAnnotations }}
        {{- include "common.tplvalues.render" (dict "value" .Values.realtime.podAnnotations "context" $) | nindent 8 }}
        {{- end }}
        checksum/default-configmap: {{ include (print $.Template.BasePath "/realtime/default-configmap.yaml") . | sha256sum }}
        {{- if .Values.realtime.extraConfig }}
        checksum/extra-configmap: {{ include (print $.Template.BasePath "/realtime/extra-configmap.yaml") . | sha256sum }}
        {{- end }}
        checksum/jwt-secret: {{ include (print $.Template.BasePath "/jwt-secret.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/realtime/secret.yaml") . | sha256sum }}
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: realtime
        {{- if .Values.realtime.podLabels }}
        {{- include "common.tplvalues.render" (dict "value" .Values.realtime.podLabels "context" $) | nindent 8 }}
        {{- end }}
        {{- if .Values.commonLabels }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ template "supabase.serviceAccountName" . }}
      {{- include "supabase.imagePullSecrets" . | nindent 6 }}
      {{- if .Values.realtime.hostAliases }}
      hostAliases: {{- include "common.tplvalues.render" (dict "value" .Values.realtime.hostAliases "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.realtime.affinity }}
      affinity: {{- include "common.tplvalues.render" ( dict "value" .Values.realtime.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.realtime.podAffinityPreset "component" "realtime" "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.realtime.podAntiAffinityPreset "component" "realtime" "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.realtime.nodeAffinityPreset.type "key" .Values.realtime.nodeAffinityPreset.key "values" .Values.realtime.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      {{- if .Values.realtime.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" ( dict "value" .Values.realtime.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.realtime.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.realtime.tolerations "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.realtime.priorityClassName }}
      priorityClassName: {{ .Values.realtime.priorityClassName | quote }}
      {{- end }}
      {{- if .Values.realtime.schedulerName }}
      schedulerName: {{ .Values.realtime.schedulerName | quote }}
      {{- end }}
      {{- if .Values.realtime.topologySpreadConstraints }}
      topologySpreadConstraints: {{- include "common.tplvalues.render" (dict "value" .Values.realtime.topologySpreadConstraints "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.realtime.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.realtime.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.realtime.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.realtime.terminationGracePeriodSeconds }}
      {{- end }}
      initContainers:
        {{- if not .Values.diagnosticMode.enabled }}
        {{- include "supabase.waitForDBInitContainer" . | nindent 8 }}
        {{- end }}
        {{- if .Values.realtime.initContainers }}
          {{- include "common.tplvalues.render" (dict "value" .Values.realtime.initContainers "context" $) | nindent 8 }}
        {{- end }}
      containers:
        - name: supabase-realtime
          image: {{ template "supabase.realtime.image" . }}
          imagePullPolicy: {{ .Values.realtime.image.pullPolicy }}
          {{- if .Values.realtime.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.realtime.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.diagnosticMode.enabled }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.command "context" $) | nindent 12 }}
          {{- else if .Values.realtime.command }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.realtime.command "context" $) | nindent 12 }}
          {{- else }}
          command:
            - /bin/bash
          {{- end }}
          {{- if .Values.diagnosticMode.enabled }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.args "context" $) | nindent 12 }}
          {{- else if .Values.realtime.args }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.realtime.args "context" $) | nindent 12 }}
          {{- else }}
          args:
            - -ec
            - |
              realtime eval Realtime.Release.migrate && realtime start
          {{- end }}
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "supabase.database.secretName" . | quote }}
                  key: {{ include "supabase.database.passwordKey" . | quote }}
            - name: API_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "supabase.jwt.secretName" . | quote }}
                  key: {{ include "supabase.jwt.secretKey" . | quote }}
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: {{ include "supabase.realtime.secretName" . | quote }}
                  key: {{ include "supabase.realtime.secretKey" . | quote }}
            {{- if .Values.realtime.extraEnvVars }}
            {{- include "common.tplvalues.render" (dict "value" .Values.realtime.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "supabase.realtime.defaultConfigmapName" . }}
            {{- if .Values.realtime.extraConfigExistingConfigmap }}
            - configMapRef:
                name: {{ include "supabase.realtime.extraConfigmapName" . }}
            {{- end }}
            {{- if .Values.realtime.extraEnvVarsCM }}
            - configMapRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.realtime.extraEnvVarsCM "context" $) }}
            {{- end }}
            {{- if .Values.realtime.extraEnvVarsSecret }}
            - secretRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.realtime.extraEnvVarsSecret "context" $) }}
            {{- end }}
          {{- if .Values.realtime.resources }}
          resources: {{- toYaml .Values.realtime.resources | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.realtime.containerPorts.http }}
          {{- if not .Values.diagnosticMode.enabled }}
          {{- if .Values.realtime.customLivenessProbe }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.realtime.customLivenessProbe "context" $) | nindent 12 }}
          {{- else if .Values.realtime.livenessProbe.enabled }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.realtime.livenessProbe "enabled") "context" $) | nindent 12 }}
            httpGet:
              path: /
              port: http
          {{- end }}
          {{- if .Values.realtime.customReadinessProbe }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.realtime.customReadinessProbe "context" $) | nindent 12 }}
          {{- else if .Values.realtime.readinessProbe.enabled }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.realtime.readinessProbe "enabled") "context" $) | nindent 12 }}
            httpGet:
              path: /
              port: http
          {{- end }}
          {{- if .Values.realtime.customStartupProbe }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" .Values.realtime.customStartupProbe "context" $) | nindent 12 }}
          {{- else if .Values.realtime.startupProbe.enabled }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.realtime.startupProbe "enabled") "context" $) | nindent 12 }}
            httpGet:
              path: /
              port: http
          {{- end }}
          {{- end }}
          {{- if .Values.realtime.lifecycleHooks }}
          lifecycle: {{- include "common.tplvalues.render" (dict "value" .Values.realtime.lifecycleHooks "context" $) | nindent 12 }}
          {{- end }}
          volumeMounts:
          {{- if .Values.realtime.extraVolumeMounts }}
          {{- include "common.tplvalues.render" (dict "value" .Values.realtime.extraVolumeMounts "context" $) | nindent 12 }}
          {{- end }}
        {{- if .Values.realtime.sidecars }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.realtime.sidecars "context" $) | nindent 8 }}
        {{- end }}
      volumes:
        {{- if .Values.realtime.extraVolumes }}
        {{- include "common.tplvalues.render" (dict "value" .Values.realtime.extraVolumes "context" $) | nindent 8 }}
        {{- end }}
{{- end }}
