{{- if (not .Values.realtime.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "supabase.realtime.secretName" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/part-of: supabase
    app.kubernetes.io/component: realtime
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  key-base: {{ include "common.secrets.passwords.manage" (dict "secret" (include "supabase.realtime.secretName" .) "key" "key-base" "providedValues" (list "realtime.keyBase") "length" 64 "context" $) }}
{{- end }}
