annotations:
  category: CMS
  licenses: Apache-2.0
apiVersion: v2
appVersion: 10.0.9
dependencies:
  - condition: mariadb.enabled
    name: mariadb
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 12.x.x
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - bitnami-common
    version: 2.x.x
description: Drupal is one of the most versatile open source content management systems in the world. It is pre-configured with the Ctools and Views modules, Drush and Let's Encrypt auto-configuration support.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/drupal/img/drupal-stack-220x234.png
keywords:
  - drupal
  - cms
  - blog
  - http
  - web
  - application
  - php
maintainers:
  - name: VMware, Inc.
    url: https://github.com/bitnami/charts
name: drupal
sources:
  - https://github.com/bitnami/charts/tree/main/bitnami/drupal
version: 14.1.3
