annotations:
  category: DeveloperTools
  licenses: Apache-2.0
apiVersion: v2
appVersion: 6.1.0
dependencies:
  - name: mongodb
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 13.x.x
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - bitnami-common
    version: 2.x.x
description: Parse is a platform that enables users to add a scalable and powerful backend to launch a full-featured app for iOS, Android, JavaScript, Windows, Unity, and more.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/parse/img/parse-stack-220x234.png
keywords:
  - parse
  - backend
  - serverless
  - platform
  - mbaas
  - mobile
maintainers:
  - name: VMware, Inc.
    url: https://github.com/bitnami/charts
name: parse
sources:
  - https://github.com/bitnami/charts/tree/main/bitnami/parse
version: 20.2.1
