annotations:
  category: ApplicationServer
  licenses: Apache-2.0
apiVersion: v2
appVersion: 10.1.8
dependencies:
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - bitnami-common
    version: 2.x.x
description: Apache Tomcat is an open-source web server designed to host and run Java-based web applications. It is a lightweight server with a good performance for applications running in production environments.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/tomcat/img/tomcat-stack-220x234.png
keywords:
  - tomcat
  - java
  - http
  - web
  - application server
  - jsp
maintainers:
  - name: VMware, Inc.
    url: https://github.com/bitnami/charts
name: tomcat
sources:
  - https://github.com/bitnami/charts/tree/main/bitnami/tomcat
version: 10.9.0
