{{- if .Values.sourceController.networkPolicy.enabled }}
kind: NetworkPolicy
apiVersion: {{ include "common.capabilities.networkPolicy.apiVersion" . }}
metadata:
  name: {{ template "flux.source-controller.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/part-of: flux
    app.kubernetes.io/component: source-controller
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  podSelector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: source-controller
  {{- if .Values.sourceController.networkPolicy.extraEgress }}
  egress: {{- include "common.tplvalues.render" ( dict "value" .Values.sourceController.networkPolicy.extraEgress "context" $ ) | nindent 4 }}
  {{- end }}
  ingress:
    # Allow inbound connections
    - ports:
        - port: {{ .Values.sourceController.containerPorts.http }}
      {{- if not .Values.sourceController.networkPolicy.allowExternal }}
      from:
        - podSelector:
            matchLabels: {{- include "common.labels.matchLabels" . | nindent 14 }}
        {{- if .Values.sourceController.networkPolicy.extraFromClauses }}
        {{- include "commot.tplvalues.render" ( dict "value" .Values.sourceController.networkPolicy.extraFromClauses "context" $ )| nindent 8 }}
        {{- end }}
        {{- if .Values.sourceController.networkPolicy.ingressNSMatchLabels }}
        - namespaceSelector:
            matchLabels:
              {{- range $key, $value := .Values.sourceController.networkPolicy.ingressNSMatchLabels }}
              {{ $key | quote }}: {{ $value | quote }}
              {{- end }}
          {{- if .Values.sourceController.networkPolicy.ingressNSPodMatchLabels }}
          podSelector:
            matchLabels:
              {{- range $key, $value := .Values.sourceController.networkPolicy.ingressNSPodMatchLabels }}
              {{ $key | quote }}: {{ $value | quote }}
              {{- end }}
          {{- end }}
        {{- end }}
      {{- end }}
    {{- if .Values.sourceController.metrics.enabled }}
    # Allow prometheus scrapes for metrics
    - ports:
        - port: {{ .Values.sourceController.containerPorts.metrics }}
    {{- end }}
    {{- if .Values.sourceController.networkPolicy.extraIngress }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.sourceController.networkPolicy.extraIngress "context" $ ) | nindent 4 }}
    {{- end }}
{{- end }}
