annotations:
  category: Database
  licenses: Apache-2.0
apiVersion: v2
appVersion: 6.0.6
dependencies:
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - bitnami-common
    version: 2.x.x
description: MongoDB(R) is an open source NoSQL database that uses JSON for data storage. MongoDB(TM) Sharded improves scalability and reliability for large datasets by distributing data across multiple machines.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/mongodb/img/mongodb-stack-220x234.png
keywords:
  - mongodb
  - database
  - nosql
  - cluster
  - replicaset
  - replication
maintainers:
  - name: VMware, Inc.
    url: https://github.com/bitnami/charts
name: mongodb-sharded
sources:
  - https://github.com/bitnami/charts/tree/main/bitnami/mongodb-sharded
version: 6.5.2
