{{- if .Values.storage.enabled }}
apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ template "supabase.storage.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/part-of: supabase
    app.kubernetes.io/component: storage
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.storage.replicaCount }}
  {{- if .Values.storage.updateStrategy }}
  strategy: {{- toYaml .Values.storage.updateStrategy | nindent 4 }}
  {{- end }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: storage
  template:
    metadata:
      annotations:
        {{- if .Values.storage.podAnnotations }}
        {{- include "common.tplvalues.render" (dict "value" .Values.storage.podAnnotations "context" $) | nindent 8 }}
        {{- end }}
        checksum/default-configmap: {{ include (print $.Template.BasePath "/storage/default-configmap.yaml") . | sha256sum }}
        {{- if .Values.storage.extraConfig }}
        checksum/extra-configmap: {{ include (print $.Template.BasePath "/storage/extra-configmap.yaml") . | sha256sum }}
        {{- end }}
        checksum/jwt-secret: {{ include (print $.Template.BasePath "/jwt-secret.yaml") . | sha256sum }}
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: storage
        {{- if .Values.storage.podLabels }}
        {{- include "common.tplvalues.render" (dict "value" .Values.storage.podLabels "context" $) | nindent 8 }}
        {{- end }}
        {{- if .Values.commonLabels }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ template "supabase.serviceAccountName" . }}
      {{- include "supabase.imagePullSecrets" . | nindent 6 }}
      {{- if .Values.storage.hostAliases }}
      hostAliases: {{- include "common.tplvalues.render" (dict "value" .Values.storage.hostAliases "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.storage.affinity }}
      affinity: {{- include "common.tplvalues.render" ( dict "value" .Values.storage.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.storage.podAffinityPreset "component" "storage" "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.storage.podAntiAffinityPreset "component" "storage" "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.storage.nodeAffinityPreset.type "key" .Values.storage.nodeAffinityPreset.key "values" .Values.storage.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      {{- if .Values.storage.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" ( dict "value" .Values.storage.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.storage.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.storage.tolerations "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.storage.priorityClassName }}
      priorityClassName: {{ .Values.storage.priorityClassName | quote }}
      {{- end }}
      {{- if .Values.storage.schedulerName }}
      schedulerName: {{ .Values.storage.schedulerName | quote }}
      {{- end }}
      {{- if .Values.storage.topologySpreadConstraints }}
      topologySpreadConstraints: {{- include "common.tplvalues.render" (dict "value" .Values.storage.topologySpreadConstraints "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.storage.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.storage.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.storage.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.storage.terminationGracePeriodSeconds }}
      {{- end }}
      initContainers:
        {{- if not .Values.diagnosticMode.enabled }}
        {{- if and .Values.volumePermissions.enabled .Values.storage.containerSecurityContext.enabled }}
        - name: volume-permissions
          image: {{ include "supabase.volumePermissions.image" . }}
          imagePullPolicy: {{ .Values.volumePermissions.image.pullPolicy | quote }}
          command:
            - sh
            - -c
            - |
              mkdir -p {{ .Values.storage.persistence.mountPath }}
              find {{ .Values.storage.persistence.mountPath }} -mindepth 1 -maxdepth 1 -not -name ".snapshot" -not -name "lost+found" | xargs chown -R {{ .Values.storage.containerSecurityContext.runAsUser }}:{{ .Values.storage.podSecurityContext.fsGroup }}
          securityContext: {{- include "common.tplvalues.render" (dict "value" .Values.volumePermissions.containerSecurityContext "context" $) | nindent 12 }}
          resources: {{- toYaml .Values.volumePermissions.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: {{ .Values.storage.persistence.mountPath }}
              subPath: {{ .Values.storage.persistence.subPath }}
        {{- end }}
        {{- include "supabase.waitForDBInitContainer" . | nindent 8 }}
        {{- end }}
        {{- if .Values.storage.initContainers }}
          {{- include "common.tplvalues.render" (dict "value" .Values.storage.initContainers "context" $) | nindent 8 }}
        {{- end }}
      containers:
        - name: supabase-storage
          image: {{ template "supabase.storage.image" . }}
          imagePullPolicy: {{ .Values.storage.image.pullPolicy }}
          {{- if .Values.storage.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.storage.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.diagnosticMode.enabled }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.command "context" $) | nindent 12 }}
          {{- else if .Values.storage.command }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.storage.command "context" $) | nindent 12 }}
          {{- else }}
          command:
            - /bin/bash
          {{- end }}
          {{- if .Values.diagnosticMode.enabled }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.args "context" $) | nindent 12 }}
          {{- else if .Values.storage.args }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.storage.args "context" $) | nindent 12 }}
          {{- else }}
          args:
            - -ec
            - |
              #!/bin/bash

              cd /opt/bitnami/supabase-storage
              pm2-runtime start ecosystem.config.js
          {{- end }}
          env:
            - name: DB_USER
              value: {{ include "supabase.database.user" . | quote }}
            - name: DB_HOST
              value: {{ include "supabase.database.host" . | quote }}
            - name: DB_PORT
              value: {{ include "supabase.database.port" . | quote }}
            - name: DB_NAME
              value: {{ include "supabase.database.name" . | quote }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "supabase.database.secretName" . }}
                  key: {{ include "supabase.database.passwordKey" . | quote }}
            - name: DATABASE_URL
              value: "postgresql://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)"
            - name: PGRST_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "supabase.jwt.secretName" . }}
                  key: {{ include "supabase.jwt.secretKey" . }}
            - name: ANON_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "supabase.jwt.secretName" . }}
                  key: {{ include "supabase.jwt.anonSecretKey" . }}
            - name: SERVICE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "supabase.jwt.secretName" . }}
                  key: {{ include "supabase.jwt.serviceSecretKey" . }}
            {{- if .Values.storage.extraEnvVars }}
            {{- include "common.tplvalues.render" (dict "value" .Values.storage.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "supabase.storage.defaultConfigmapName" . }}
            {{- if .Values.storage.extraConfigExistingConfigmap }}
            - configMapRef:
                name: {{ include "supabase.storage.extraConfigmapName" . }}
            {{- end }}
            {{- if .Values.storage.extraEnvVarsCM }}
            - configMapRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.storage.extraEnvVarsCM "context" $) }}
            {{- end }}
            {{- if .Values.storage.extraEnvVarsSecret }}
            - secretRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.storage.extraEnvVarsSecret "context" $) }}
            {{- end }}
          {{- if .Values.storage.resources }}
          resources: {{- toYaml .Values.storage.resources | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.storage.containerPorts.http }}
          {{- if not .Values.diagnosticMode.enabled }}
          {{- if .Values.storage.customLivenessProbe }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.storage.customLivenessProbe "context" $) | nindent 12 }}
          {{- else if .Values.storage.livenessProbe.enabled }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.storage.livenessProbe "enabled") "context" $) | nindent 12 }}
            httpGet:
              path: /status
              port: http
          {{- end }}
          {{- if .Values.storage.customReadinessProbe }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.storage.customReadinessProbe "context" $) | nindent 12 }}
          {{- else if .Values.storage.readinessProbe.enabled }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.storage.readinessProbe "enabled") "context" $) | nindent 12 }}
            httpGet:
              path: /status
              port: http
          {{- end }}
          {{- if .Values.storage.customStartupProbe }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" .Values.storage.customStartupProbe "context" $) | nindent 12 }}
          {{- else if .Values.storage.startupProbe.enabled }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.storage.startupProbe "enabled") "context" $) | nindent 12 }}
            httpGet:
              path: /status
              port: http
          {{- end }}
          {{- end }}
          {{- if .Values.storage.lifecycleHooks }}
          lifecycle: {{- include "common.tplvalues.render" (dict "value" .Values.storage.lifecycleHooks "context" $) | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: data
              mountPath: {{ .Values.storage.persistence.mountPath }}
              {{- if .Values.storage.persistence.subPath }}
              subPath: {{ .Values.storage.persistence.subPath }}
              {{- end }}
          {{- if .Values.storage.extraVolumeMounts }}
          {{- include "common.tplvalues.render" (dict "value" .Values.storage.extraVolumeMounts "context" $) | nindent 12 }}
          {{- end }}
        {{- if .Values.storage.sidecars }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.storage.sidecars "context" $) | nindent 8 }}
        {{- end }}
      volumes:
        - name: data
        {{- if .Values.storage.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ default (include "supabase.storage.fullname" .) .Values.storage.persistence.existingClaim }}
        {{- else }}
          emptyDir: {}
        {{- end }}
        {{- if .Values.storage.extraVolumes }}
        {{- include "common.tplvalues.render" (dict "value" .Values.storage.extraVolumes "context" $) | nindent 8 }}
        {{- end }}
{{- end }}
