{{- if eq .Values.mode "distributed" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-scheduler" (include "common.names.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: scheduler
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.scheduler.service.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.scheduler.service.annotations "context" $) | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.scheduler.service.type }}
  {{- if and .Values.scheduler.service.clusterIP (eq .Values.scheduler.service.type "ClusterIP") }}
  clusterIP: {{ .Values.scheduler.service.clusterIP }}
  {{- end }}
  {{- if .Values.scheduler.service.sessionAffinity }}
  sessionAffinity: {{ .Values.scheduler.service.sessionAffinity }}
  {{- end }}
  {{- if .Values.scheduler.service.sessionAffinityConfig }}
  sessionAffinityConfig: {{- include "common.tplvalues.render" (dict "value" .Values.scheduler.service.sessionAffinityConfig "context" $) | nindent 4 }}
  {{- end }}
  {{- if or (eq .Values.scheduler.service.type "LoadBalancer") (eq .Values.scheduler.service.type "NodePort") }}
  externalTrafficPolicy: {{ .Values.scheduler.service.externalTrafficPolicy | quote }}
  {{- end }}
  {{- if and (eq .Values.scheduler.service.type "LoadBalancer") (not (empty .Values.scheduler.service.loadBalancerSourceRanges)) }}
  loadBalancerSourceRanges: {{ .Values.scheduler.service.loadBalancerSourceRanges }}
  {{- end }}
  {{- if and (eq .Values.scheduler.service.type "LoadBalancer") (not (empty .Values.scheduler.service.loadBalancerIP)) }}
  loadBalancerIP: {{ .Values.scheduler.service.loadBalancerIP }}
  {{- end }}
  ports:
    - port: {{ .Values.scheduler.service.ports.mxnet}}
      targetPort: mxnet
      name: mxnet
      {{- if and (or (eq .Values.scheduler.service.type "NodePort") (eq .Values.scheduler.service.type "LoadBalancer")) (not (empty .Values.scheduler.service.nodePorts.mxnet)) }}
      nodePort: {{ .Values.scheduler.service.nodePorts.mxnet }}
      {{- else if eq .Values.scheduler.service.type "ClusterIP" }}
      nodePort: null
      {{- end }}
    {{- if .Values.scheduler.service.extraPorts }}
    {{- include "common.tplvalues.render" (dict "value" .Values.scheduler.service.extraPorts "context" $) | nindent 4 }}
    {{- end }}
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: scheduler
{{- end }}
