{{- if and ( include "elasticsearch.coordinating.enabled" . ) .Values.coordinating.pdb.create }}
apiVersion: {{ include "common.capabilities.policy.apiVersion" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ include "elasticsearch.coordinating.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: coordinating-only
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" (dict "value" .Values.commonLabels "context" $) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.coordinating.pdb.minAvailable }}
  minAvailable: {{ .Values.coordinating.pdb.minAvailable }}
  {{- end }}
  {{- if .Values.coordinating.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.coordinating.pdb.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: coordinating-only
{{- end }}
