{{- if .Values.collectd.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}-collectd
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: influxdb
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" (dict "value" .Values.commonAnnotations "context" $) | nindent 4 }}
    {{- end }}
    {{- if .Values.collectd.service.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.collectd.service.annotations "context" $) | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.collectd.service.type }}
  {{- if and .Values.collectd.service.clusterIP (eq .Values.collectd.service.type "ClusterIP") }}
  clusterIP: {{ .Values.collectd.service.clusterIP }}
  {{- end }}
  {{- if (or (eq .Values.collectd.service.type "LoadBalancer") (eq .Values.collectd.service.type "NodePort")) }}
  externalTrafficPolicy: {{ .Values.collectd.service.externalTrafficPolicy | quote }}
  {{- end }}
  {{ if eq .Values.collectd.service.type "LoadBalancer" }}
  loadBalancerSourceRanges: {{ .Values.collectd.service.loadBalancerSourceRanges }}
  {{ end }}
  {{- if (and (eq .Values.collectd.service.type "LoadBalancer") (not (empty .Values.collectd.service.loadBalancerIP))) }}
  loadBalancerIP: {{ .Values.collectd.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.collectd.service.sessionAffinity }}
  sessionAffinity: {{ .Values.collectd.service.sessionAffinity }}
  {{- end }}
  {{- if .Values.collectd.service.sessionAffinityConfig }}
  sessionAffinityConfig: {{- include "common.tplvalues.render" (dict "value" .Values.collectd.service.sessionAffinityConfig "context" $) | nindent 4 }}
  {{- end }}
  ports:
    - port: {{ .Values.collectd.service.port }}
      targetPort: {{ .Values.collectd.service.port }}
      protocol: UDP
      name: udp
      {{- if (and (or (eq .Values.collectd.service.type "NodePort") (eq .Values.collectd.service.type "LoadBalancer")) (not (empty .Values.collectd.service.nodePort))) }}
      nodePort: {{ .Values.collectd.service.nodePort }}
      {{- else if eq .Values.collectd.service.type "ClusterIP" }}
      nodePort: null
      {{- end }}
    {{- if .Values.collectd.service.extraPorts }}
    {{- include "common.tplvalues.render" (dict "value" .Values.collectd.service.extraPorts "context" $) | nindent 4 }}
    {{- end }}
  selector:
    {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: influxdb
{{- end }}
