annotations:
  category: Database
  licenses: Apache-2.0
apiVersion: v2
appVersion: 2.7.1
dependencies:
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - bitnami-common
    version: 2.x.x
description: InfluxDB(TM) is an open source time-series database. It is a core component of the TICK (Telegraf, InfluxDB(TM), Chronograf, Kapacitor) stack.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/influxdb/img/influxdb-stack-220x234.png
keywords:
  - influxdb
  - tick
  - database
  - timeseries
maintainers:
  - name: VMware, Inc.
    url: https://github.com/bitnami/charts
name: influxdb
sources:
  - https://github.com/bitnami/charts/tree/main/bitnami/influxdb
version: 5.6.0
