{{- if (include "kong.createExternalDBSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-external-secret" (include "common.names.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: server
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if eq .Values.database "cassandra" }}
  cassandra-password: {{ .Values.cassandra.external.password | b64enc | quote }}
  {{- end }}
  {{- if eq .Values.database "postgresql" }}
  password: {{ .Values.postgresql.external.password | b64enc | quote }}
  {{- end }}
{{- end }}
