{{- if .Values.meta.enabled }}
apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ template "supabase.meta.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/part-of: supabase
    app.kubernetes.io/component: meta
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.meta.replicaCount }}
  {{- if .Values.meta.updateStrategy }}
  strategy: {{- toYaml .Values.meta.updateStrategy | nindent 4 }}
  {{- end }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: meta
  template:
    metadata:
      annotations:
        {{- if .Values.meta.podAnnotations }}
        {{- include "common.tplvalues.render" (dict "value" .Values.meta.podAnnotations "context" $) | nindent 8 }}
        {{- end }}
        checksum/default-configmap: {{ include (print $.Template.BasePath "/meta/default-configmap.yaml") . | sha256sum }}
        {{- if .Values.meta.extraConfig }}
        checksum/extra-configmap: {{ include (print $.Template.BasePath "/meta/extra-configmap.yaml") . | sha256sum }}
        {{- end }}
        checksum/jwt-secret: {{ include (print $.Template.BasePath "/jwt-secret.yaml") . | sha256sum }}
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: meta
        {{- if .Values.meta.podLabels }}
        {{- include "common.tplvalues.render" (dict "value" .Values.meta.podLabels "context" $) | nindent 8 }}
        {{- end }}
        {{- if .Values.commonLabels }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ template "supabase.serviceAccountName" . }}
      {{- include "supabase.imagePullSecrets" . | nindent 6 }}
      {{- if .Values.meta.hostAliases }}
      hostAliases: {{- include "common.tplvalues.render" (dict "value" .Values.meta.hostAliases "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.meta.affinity }}
      affinity: {{- include "common.tplvalues.render" ( dict "value" .Values.meta.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.meta.podAffinityPreset "component" "meta" "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.meta.podAntiAffinityPreset "component" "meta" "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.meta.nodeAffinityPreset.type "key" .Values.meta.nodeAffinityPreset.key "values" .Values.meta.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      {{- if .Values.meta.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" ( dict "value" .Values.meta.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.meta.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.meta.tolerations "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.meta.priorityClassName }}
      priorityClassName: {{ .Values.meta.priorityClassName | quote }}
      {{- end }}
      {{- if .Values.meta.schedulerName }}
      schedulerName: {{ .Values.meta.schedulerName | quote }}
      {{- end }}
      {{- if .Values.meta.topologySpreadConstraints }}
      topologySpreadConstraints: {{- include "common.tplvalues.render" (dict "value" .Values.meta.topologySpreadConstraints "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.meta.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.meta.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.meta.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.meta.terminationGracePeriodSeconds }}
      {{- end }}
      initContainers:
        {{- if not .Values.diagnosticMode.enabled }}
        {{- include "supabase.waitForDBInitContainer" . | nindent 8 }}
        {{- end }}
        {{- if .Values.meta.initContainers }}
          {{- include "common.tplvalues.render" (dict "value" .Values.meta.initContainers "context" $) | nindent 8 }}
        {{- end }}
      containers:
        - name: supabase-postgres-meta
          image: {{ template "supabase.meta.image" . }}
          imagePullPolicy: {{ .Values.meta.image.pullPolicy }}
          {{- if .Values.meta.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.meta.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.diagnosticMode.enabled }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.command "context" $) | nindent 12 }}
          {{- else if .Values.meta.command }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.meta.command "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.diagnosticMode.enabled }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.args "context" $) | nindent 12 }}
          {{- else if .Values.meta.args }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.meta.args "context" $) | nindent 12 }}
          {{- end }}
          env:
            - name: PG_META_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "supabase.database.secretName" . }}
                  key: {{ include "supabase.database.passwordKey" . | quote }}
            {{- if .Values.meta.extraEnvVars }}
            {{- include "common.tplvalues.render" (dict "value" .Values.meta.extraEnvVars "context" $) | nindent 12 }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "supabase.meta.defaultConfigmapName" . }}
            {{- if .Values.meta.extraConfigExistingConfigmap }}
            - configMapRef:
                name: {{ include "supabase.meta.extraConfigmapName" . }}
            {{- end }}
            {{- if .Values.meta.extraEnvVarsCM }}
            - configMapRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.meta.extraEnvVarsCM "context" $) }}
            {{- end }}
            {{- if .Values.meta.extraEnvVarsSecret }}
            - secretRef:
                name: {{ include "common.tplvalues.render" (dict "value" .Values.meta.extraEnvVarsSecret "context" $) }}
            {{- end }}
          {{- if .Values.meta.resources }}
          resources: {{- toYaml .Values.meta.resources | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.meta.containerPorts.http }}
          {{- if not .Values.diagnosticMode.enabled }}
          {{- if .Values.meta.customLivenessProbe }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.meta.customLivenessProbe "context" $) | nindent 12 }}
          {{- else if .Values.meta.livenessProbe.enabled }}
          livenessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.meta.livenessProbe "enabled") "context" $) | nindent 12 }}
            httpGet:
              path: /health
              port: http
          {{- end }}
          {{- if .Values.meta.customReadinessProbe }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" .Values.meta.customReadinessProbe "context" $) | nindent 12 }}
          {{- else if .Values.meta.readinessProbe.enabled }}
          readinessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.meta.readinessProbe "enabled") "context" $) | nindent 12 }}
            httpGet:
              path: /health
              port: http
          {{- end }}
          {{- if .Values.meta.customStartupProbe }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" .Values.meta.customStartupProbe "context" $) | nindent 12 }}
          {{- else if .Values.meta.startupProbe.enabled }}
          startupProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.meta.startupProbe "enabled") "context" $) | nindent 12 }}
            httpGet:
              path: /health
              port: http
          {{- end }}
          {{- end }}
          {{- if .Values.meta.lifecycleHooks }}
          lifecycle: {{- include "common.tplvalues.render" (dict "value" .Values.meta.lifecycleHooks "context" $) | nindent 12 }}
          {{- end }}
          volumeMounts:
          {{- if .Values.meta.extraVolumeMounts }}
          {{- include "common.tplvalues.render" (dict "value" .Values.meta.extraVolumeMounts "context" $) | nindent 12 }}
          {{- end }}
        {{- if .Values.meta.sidecars }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.meta.sidecars "context" $) | nindent 8 }}
        {{- end }}
      volumes:
        {{- if .Values.meta.extraVolumes }}
        {{- include "common.tplvalues.render" (dict "value" .Values.meta.extraVolumes "context" $) | nindent 8 }}
        {{- end }}
{{- end }}
