annotations:
  category: Analytics
  licenses: Apache-2.0
apiVersion: v2
appVersion: 1.19.3
dependencies:
  - condition: postgresql.enabled
    name: postgresql
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 12.x.x
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - bitnami-common
    version: 2.x.x
description: Gitea is a lightweight code hosting solution. Written in Go, features low resource consumption, easy upgrades and multiple databases.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/gitea/img/gitea-stack-220x234.png
keywords:
  - gitea
  - analytics
  - http
  - web
  - application
  - php
maintainers:
  - name: VMware, Inc.
    url: https://github.com/bitnami/charts
name: gitea
sources:
  - https://github.com/bitnami/charts/tree/main/bitnami/gitea
version: 0.3.1
