{{- if .Values.server.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-headless" (include "vault.server.fullname" .) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: http
      port: {{ .Values.server.service.general.ports.http }}
      targetPort: http
    - name: https-internal
      port: {{ .Values.server.service.general.ports.internal }}
      targetPort: https-internal
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/part-of: vault
    app.kubernetes.io/component: server
{{- end }}
