apiVersion: v1
kind: Service
metadata:
  name: {{ template "grafana-mimir.gossip-ring.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/part-of: grafana-mimir
    app.kubernetes.io/component: mimir
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.commonAnnotations .Values.mimir.gossipRing.service.annotations }}
  annotations:
    {{- if .Values.mimir.gossipRing.service.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.mimir.gossipRing.service.annotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: ClusterIP
  publishNotReadyAddresses: true
  clusterIP: None
  ports:
    - name: http
      port: {{ .Values.mimir.gossipRing.service.ports.http }}
      targetPort: http-memberlist
      protocol: TCP
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
    mimir-gossip-member: "true"
