{{- if .Values.networkPolicy.enabled }}
kind: NetworkPolicy
apiVersion: {{ include "common.capabilities.networkPolicy.apiVersion" . }}
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  podSelector:
    matchLabels: {{ include "common.labels.matchLabels" . | nindent 6 }}
  ingress:
    - ports:
        - port: {{ .Values.service.ports.client }}
      {{- if not .Values.networkPolicy.allowExternal }}
      from:
        - podSelector:
            matchLabels:
              {{ template "common.names.fullname" . }}-client: "true"
      {{- end }}
    - ports:
        - port: {{ .Values.service.ports.cluster }}
    - ports:
        - port: {{ .Values.service.ports.monitoring }}
    {{- if .Values.metrics.enabled }}
    - ports:
        - port: {{ .Values.metrics.service.port }}
    {{- end }}
{{- end }}
