annotations:
  category: Infrastructure
  licenses: Apache-2.0
apiVersion: v2
appVersion: 2.387.3
dependencies:
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - bitnami-common
    version: 2.x.x
description: Jenkins is an open source Continuous Integration and Continuous Delivery (CI/CD) server designed to automate the building, testing, and deploying of any software project.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/jenkins/img/jenkins-stack-220x234.png
keywords:
  - jenkins
  - ci
  - cd
  - http
  - web
  - application
maintainers:
  - name: VMware, Inc.
    url: https://github.com/bitnami/charts
name: jenkins
sources:
  - https://github.com/bitnami/charts/tree/main/bitnami/jenkins
version: 12.2.0
