{{- if .Values.ruler.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "grafana-mimir.ruler.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/part-of: grafana-mimir
    app.kubernetes.io/component: ruler
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.commonAnnotations .Values.ruler.service.annotations }}
  annotations:
    {{- if .Values.ruler.service.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.ruler.service.annotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.ruler.service.type }}
  {{- if .Values.ruler.service.sessionAffinity }}
  sessionAffinity: {{ .Values.ruler.service.sessionAffinity }}
  {{- end }}
  {{- if .Values.ruler.service.sessionAffinityConfig }}
  sessionAffinityConfig: {{- include "common.tplvalues.render" (dict "value" .Values.ruler.service.sessionAffinityConfig "context" $) | nindent 4 }}
  {{- end }}
  {{- if .Values.ruler.service.clusterIP }}
  clusterIP: {{ .Values.ruler.service.clusterIP }}
  {{- end }}
  {{- if (or (eq .Values.ruler.service.type "LoadBalancer") (eq .Values.ruler.service.type "NodePort")) }}
  externalTrafficPolicy: {{ .Values.ruler.service.externalTrafficPolicy | quote }}
  {{- end }}
  {{ if eq .Values.ruler.service.type "LoadBalancer" }}
  loadBalancerSourceRanges: {{ .Values.ruler.service.loadBalancerSourceRanges }}
  {{ end }}
  {{- if (and (eq .Values.ruler.service.type "LoadBalancer") (not (empty .Values.ruler.service.loadBalancerIP))) }}
  loadBalancerIP: {{ .Values.ruler.service.loadBalancerIP }}
  {{- end }}
  ports:
    - name: http
      port: {{ .Values.ruler.service.ports.http }}
      targetPort: http
      protocol: TCP
      {{- if (and (or (eq .Values.ruler.service.type "NodePort") (eq .Values.ruler.service.type "LoadBalancer")) (not (empty .Values.ruler.service.nodePorts.http))) }}
      nodePort: {{ .Values.ruler.service.nodePorts.http }}
      {{- else if eq .Values.ruler.service.type "ClusterIP" }}
      nodePort: null
      {{- end }}
    - name: grpc
      port: {{ .Values.ruler.service.ports.grpc }}
      targetPort: grpc
      protocol: TCP
      {{- if (and (or (eq .Values.ruler.service.type "NodePort") (eq .Values.ruler.service.type "LoadBalancer")) (not (empty .Values.ruler.service.nodePorts.grpc))) }}
      nodePort: {{ .Values.ruler.service.nodePorts.grpc }}
      {{- else if eq .Values.ruler.service.type "ClusterIP" }}
      nodePort: null
      {{- end }}
    {{- if .Values.ruler.service.extraPorts }}
    {{- include "common.tplvalues.render" (dict "value" .Values.ruler.service.extraPorts "context" $) | nindent 4 }}
    {{- end }}
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/part-of: grafana-mimir
    app.kubernetes.io/component: ruler
{{- end }}
