annotations:
  category: E-Commerce
  licenses: Apache-2.0
apiVersion: v2
appVersion: 4.0.2-1
dependencies:
  - condition: mariadb.enabled
    name: mariadb
    repository: oci://registry-1.docker.io/bitnamicharts
    version: 12.x.x
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - bitnami-common
    version: 2.x.x
description: OpenCart is free open source ecommerce platform for online merchants. OpenCart provides a professional and reliable foundation from which to build a successful online store.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/opencart/img/opencart-stack-220x234.png
keywords:
  - opencart
  - e-commerce
  - http
  - web
  - php
maintainers:
  - name: VMware, Inc.
    url: https://github.com/bitnami/charts
name: opencart
sources:
  - https://github.com/bitnami/charts/tree/main/bitnami/opencart
version: 14.1.1
