{{- if and .Values.concierge.enabled .Values.concierge.serviceAccount.impersonationProxy.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "pinniped.concierge.impersonation-proxy.serviceAccountName" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/part-of: pinniped
    app.kubernetes.io/component: concierge
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.concierge.serviceAccount.impersonationProxy.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.concierge.serviceAccount.impersonationProxy.annotations "context" $ ) | nindent 4 }}
    {{- end }}
automountServiceAccountToken: {{ .Values.concierge.serviceAccount.impersonationProxy.automountServiceAccountToken }}
secrets:
  - name: {{ template "pinniped.concierge.impersonation-proxy.fullname" . }}
{{- end }}
