{{- if .Values.concierge.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "pinniped.concierge.impersonation-proxy.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/part-of: pinniped
    app.kubernetes.io/component: concierge
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  annotations:
    kubernetes.io/service-account.name: {{ template "pinniped.concierge.impersonation-proxy.serviceAccountName" . }}
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
type: kubernetes.io/service-account-token
{{- end }}
