{{- if and .Values.kong.declarativeConfig (not .Values.kong.declarativeConfigCM) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kong.declarativeConfigMap" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: server
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  kong.yml: |-
    {{- include "common.tplvalues.render" (dict "value" .Values.kong.declarativeConfig "context" $) | nindent 4 }}
{{- end }}
