{{- if and .Values.supervisor.enabled (not .Values.supervisor.existingConfigmap) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "pinniped.supervisor.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/part-of: pinniped
    app.kubernetes.io/component: supervisor
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  pinniped.yaml: |-
    {{- include "common.tplvalues.render" (dict "value" .Values.supervisor.configuration "context" $) | nindent 4 }}
{{- end }}
