{{- if .Values.concierge.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "pinniped.concierge.fullname" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/part-of: pinniped
    app.kubernetes.io/component: concierge
    {{- if .Values.concierge.service.labels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.concierge.service.labels "context" $ ) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.concierge.service.annotations .Values.commonAnnotations }}
  annotations:
    {{- if .Values.concierge.service.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.concierge.service.annotations "context" $) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: {{ .Values.concierge.service.type }}
  {{- if and .Values.concierge.service.clusterIP (eq .Values.concierge.service.type "ClusterIP") }}
  clusterIP: {{ .Values.concierge.service.clusterIP }}
  {{- end }}
  {{- if .Values.concierge.service.sessionAffinity }}
  sessionAffinity: {{ .Values.concierge.service.sessionAffinity }}
  {{- end }}
  {{- if .Values.concierge.service.sessionAffinityConfig }}
  sessionAffinityConfig: {{- include "common.tplvalues.render" (dict "value" .Values.concierge.service.sessionAffinityConfig "context" $) | nindent 4 }}
  {{- end }}
  {{- if or (eq .Values.concierge.service.type "LoadBalancer") (eq .Values.concierge.service.type "NodePort") }}
  externalTrafficPolicy: {{ .Values.concierge.service.externalTrafficPolicy | quote }}
  {{- end }}
  {{- if and (eq .Values.concierge.service.type "LoadBalancer") (not (empty .Values.concierge.service.loadBalancerSourceRanges)) }}
  loadBalancerSourceRanges: {{ .Values.concierge.service.loadBalancerSourceRanges }}
  {{- end }}
  {{- if and (eq .Values.concierge.service.type "LoadBalancer") (not (empty .Values.concierge.service.loadBalancerIP)) }}
  loadBalancerIP: {{ .Values.concierge.service.loadBalancerIP }}
  {{- end }}
  ports:
    - name: https
      port: {{ .Values.concierge.service.ports.https }}
      protocol: TCP
      targetPort: https-proxy
      {{- if and (or (eq .Values.concierge.service.type "NodePort") (eq .Values.concierge.service.type "LoadBalancer")) (not (empty .Values.concierge.service.nodePorts.https)) }}
      nodePort: {{ .Values.concierge.service.nodePorts.https }}
      {{- else if eq .Values.concierge.service.type "ClusterIP" }}
      nodePort: null
      {{- end }}
    {{- if .Values.concierge.service.extraPorts }}
    {{- include "common.tplvalues.render" (dict "value" .Values.concierge.service.extraPorts "context" $) | nindent 4 }}
    {{- end }}
  selector: {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: concierge
{{- end }}
