annotations:
  category: Infrastructure
  licenses: Apache-2.0
apiVersion: v2
appVersion: 0.36.1
dependencies:
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    tags:
      - bitnami-common
    version: 2.x.x
description: Flux is a tool for keeping Kubernetes clusters in sync with sources of configuration
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/fluxcd-kustomize-controller/img/fluxcd-kustomize-controller-stack-220x234.png
keywords:
  - deployment
  - gitops
  - cd
  - continuous-delivery
  - helm
  - kustomize
maintainers:
  - name: VMware, Inc.
    url: https://github.com/bitnami/charts
name: flux
sources:
  - https://github.com/bitnami/charts/tree/main/bitnami/flux
version: 0.3.0
